# Generated by Django 5.2.4 on 2025-07-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('tipo_empresa', models.CharField(choices=[('farmacia', 'Farmacia'), ('ropa', 'Tienda de Ropa'), ('abarrotes', 'Tienda de Abarrotes'), ('restaurante', 'Restaurante'), ('otros', 'Otros')], max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo_url', models.URLField(blank=True)),
                ('plan_suscripcion', models.CharField(default='free', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
